# Generated by Django 5.1.7 on 2025-03-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_link',
            field=models.CharField(max_length=255),
        ),
    ]
